platform :ios, '14.0'
source 'https://github.com/S1rent/Dicoding-CorePodSpecs'
 
use_frameworks!
workspace 'Comflix'

target 'Comflix' do
  pod 'Alamofire'
  pod 'SwiftLint'
  pod 'SDWebImageSwiftUI'
  pod 'RealmSwift'
  pod 'Core'
end

target 'Movie' do
  pod 'Core'
  project '../Movie/Movie'
  pod 'RealmSwift'
  pod 'Alamofire'
end

target 'Profile' do
  pod 'Core'
  project '../Profile/Profile'
  pod 'RealmSwift'
end

target 'Home' do
  project '../Movie/Movie'
  project '../Home/Home'
  pod 'RealmSwift'
end

target 'Detail' do
  project '../Movie/Movie'	
  project '../Detail/Detail'
  pod 'SDWebImageSwiftUI'
end

target 'Favorite' do
  project '../Movie/Movie'
  project '../Favorite/Favorite'
  pod 'SDWebImageSwiftUI'
end
